name: "Release"

on:
  release:
    types:
      - "published"

permissions: {}

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"
    permissions:
      contents: write
    steps:
      - name: "Checkout the repository"
        uses: "actions/checkout@v4.2.1"

      - name: "Adjust version number"
        shell: "bash"
        run: |
          cat <(echo "req") "${{ github.workspace }}/custom_components/idm_heatpump/requirements.txt" | \
            yq -p=csv -ojson '[.[].req]' | \
            yq eval-all -i 'select(fi==0).requirements=select(fi==1)|select(fi==0)|.version="${{ github.event.release.tag_name }}"' \
            "${{ github.workspace }}/custom_components/idm_heatpump/manifest.json" -

      - name: "ZIP the integration directory"
        shell: "bash"
        run: |
          cd "${{ github.workspace }}/custom_components/idm_heatpump"
          zip idm_heatpump.zip -r ./

      - name: "Upload the ZIP file to the release"
        uses: softprops/action-gh-release@v2.0.8
        with:
          files: ${{ github.workspace }}/custom_components/idm_heatpump/idm_heatpump.zip
